### ISSUE TITLE
Game Crashes on start up since recent update

### ISSUE THREAD

**Issue by Gizmo8989** [skairunner/sky-oni-mods#114]
System.TypeLoadException: Could not resolve type with token 01000026 from typeref (expected class 'Worker' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
at (wrapper managed-to-native)

**Comment by pakvg85** [comment]
now crashing with
`System.ArgumentException: Undefined target method for patch method static System.Void DiseasesReimagined.BaseMinionConfig_CreatePrefab_Patch::Postfix(UnityEngine.GameObject __result)`
probably class' name was confused? `MinionConfig <-> BaseMinionConfig`

**Comment by skairunner** [comment]
Should be resolved by https://github.com/skairunner/sky-oni-mods/pull/117 , it does seem that the beta branch and main game had different method names.

**Comment by pakvg85** [comment]
seem to be fine now, thank you ❤
