### ISSUE TITLE
Piped output for petroleum generator (PW) no longer working with CR

### ISSUE THREAD

**Issue by Yaslana** [skairunner/sky-oni-mods#14]
Like title says, since the last update there seems to be some compatibility problem with piped outputs. On weekend everything worked fine. I also had some really bad framedrops while power generators were working but a reinstall of the mod seems to have helped here. I am using the steam mod. It says v. 1.1 while using the mod manager mod, but I can change nat gas output so I seem to have the current version?

**Comment by skairunner** [comment]
Hi,

Can you attach your log file? It is located
at C:\Users\%USERNAME%\AppData\LocalLow\Klei\Oxygen Not
Included\output_log.txt on Windows.

Also, can you describe what you mean by "not work"? Does the petrol
generator simply not output anything, or does it output the wrong amount?

**Comment by Yaslana** [comment]
Oh I am sorry, I mean I mean it dribbles everything on the floor, not using the output at all. The piped output works fine when I deactivate CR.
[output_log.txt](https://github.com/skairunner/sky-oni-mods/files/3757492/output_log.txt)

**Comment by Yaslana** [comment]
Thanks for the fast fix! It still says 1.1 for me but the output works :)

**Comment by skairunner** [comment]
That's great! It seems that Ony's Mod Manager is using the wrong version
for display--it should use AssemblyFileVersion, not AssemblyVersion. I
suggest you ask her to fix it for accurate information!
