### ISSUE TITLE
Expanded Lights - Stock lights does not show lit area in preview

### ISSUE THREAD

**Issue by mrstoned-gh** [skairunner/sky-oni-mods#21]
The stock ceiling and floorlamp no longer show preview lit area.
I have no other lights mods (except lights out).

The floodlight do show lit preview.
![20191117034327_1](https://user-images.githubusercontent.com/40145223/69002299-cd6d0700-08ec-11ea-9f75-569abf3d5343.jpg)
![20191117034336_1](https://user-images.githubusercontent.com/40145223/69002300-cd6d0700-08ec-11ea-8281-df223100841b.jpg)
![20191117034343_1](https://user-images.githubusercontent.com/40145223/69002301-cd6d0700-08ec-11ea-87c7-357564ec77eb.jpg)

**Comment by skairunner** [comment]
Thank you for reporting this issue. It happens to all PLib lights, I
believe, and I'll look into it along with the plib author to figure out
what's going on.

**Comment by skairunner** [comment]
Fixed this issue in 4befc521347d0a66de40436f68586ffef7a3db55 . Thank you for reporting it!
