### ISSUE TITLE
Storage Pod - Update on 2020/01/04 broke some stuff

### ISSUE THREAD

**Issue by cheetah2003** [skairunner/sky-oni-mods#52]
So this recent update broke a couple things.

1. It erased all pre-existing configuration.
2. It's displaying exponentials for capacity on mod configuration screen.  I typed in 1000 and it did this:

![image](https://user-images.githubusercontent.com/227573/103601456-865e1e80-4ebe-11eb-94ee-f4096de2a9d3.png)

**Comment by skairunner** [comment]
The exponents might be a PLib change, because nothing else in the code changed. The capacity was always a float.

**Comment by skairunner** [comment]
Fixed the formatting in 9938898e2630c06393f5603ccd25d7d267787859
