### ISSUE TITLE
crash after clicking on a infected dupe

### ISSUE THREAD

**Issue by eL-Du-de** [skairunner/sky-oni-mods#62]
I play with DLC, maybe the crash log helps..

NullReferenceException: Object reference not set to an instance of an object

DiseasesReimagined.GermExposurePatch.CreateOneImmuneInfo (Klei.AI.Disease disease, UnityEngine.GameObject target, DiseasesReimagined.GermIntegrator integrator, CollapsibleDetailContentPanel panel) (at <57c20e6d0834437583ac541615578f47>:0)
DiseasesReimagined.GermExposurePatch.CreateImmuneInfo (CollapsibleDetailContentPanel immuneSystemPanel, UnityEngine.GameObject target) (at <57c20e6d0834437583ac541615578f47>:0)
DiseasesReimagined.GermExposurePatch+DiseaseInfoScreen_CreateImmuneInfo_Patch.Prefix (UnityEngine.GameObject ___selectedTarget, System.Boolean& __result, CollapsibleDetailContentPanel ___immuneSystemPanel) (at <57c20e6d0834437583ac541615578f47>:0)
(wrapper dynamic-method) DiseaseInfoScreen.DiseaseInfoScreen.CreateImmuneInfo_Patch1(DiseaseInfoScreen)
DiseaseInfoScreen.Refresh () (at <06f8e7422a7d4d098b0ee5ec07bdf81a>:0)
DiseaseInfoScreen.LateUpdate () (at <06f8e7422a7d4d098b0ee5ec07bdf81a>:0)

Build: EX1 S14-472345-SD

**Comment by skairunner** [comment]
Hi, I've pretty much not been modding or playing Oxygen Not Included for the last while. Unless someone contributes a fix, it's unlikely that any of my mods will continue to be playable. I'm sorry for the inconvenience 😔
