### ISSUE TITLE
Cool Pod Has Two Overlapping Automation Ports

### ISSUE THREAD

**Issue by TroublesomeCorvid** [skairunner/sky-oni-mods#68]
It has both an automation input and an automation output on a building that is only one tile in size, so they overlap with each other and cannot be placed/built.

Not sure why or how that happened, but it happened.  If anyone wants to fix this, I suggest removing the input port (enable/disable), as I can't imagine why you would want to turn off a refrigerator.

**Comment by yeliabmit** [comment]
There is nothing more annoying than a post simply bumping an issue -- but I am going to be that guy.  This remains unresolved and renders the Cool Pod worthless and also frustratingly out of reach.
