### ISSUE TITLE
Symptoms continue

### ISSUE THREAD

**Issue by GamerGabby777** [skairunner/sky-oni-mods#82]
Whenever dupes get ill, even after they are completely cured their side effects (Such as coughing) last for the rest of time.

**Comment by GamerGabby777** [comment]
In diseased restored

**Comment by aantono** [comment]
I get the same problem.  My dupe got Food Poisoning and after being cured it continues to Vomit all over the place, but the stats don't show any Food Poisoning germs on them or being sick in any way. :(
