### ISSUE TITLE
dupes won't stop washing their hands [DR]

### ISSUE THREAD

**Issue by Lbphero** [skairunner/sky-oni-mods#9]
Very Likely a compatibility issue with the mod that adds queues to sinks, but I think we'd all like for there to be compatibility between those two.
![ezgif com-crop (1)](https://user-images.githubusercontent.com/31712498/66691239-0eb92980-ec52-11e9-9ef0-e87f3e1eeed6.gif)

**Comment by peterhaneve** [comment]
Should be fixed by a61a884
