### ISSUE TITLE
Issue on Expanded Lights

### ISSUE THREAD

**Issue by iDaisukei** [skairunner/sky-oni-mods#92]
Expanded lights is currently having issues with the new ONI update. Some light sources, base and mod sources, only emit 1 tile of lux instead of the usual. Requesting for an update if possible please.

**Comment by TroublesomeCorvid** [comment]
Same: all light sources limited to illuminating a single tile.  If I had to guess, it looks like the new update did something to how the effective range of light emitting buildings is parsed.

**Comment by devent** [comment]
Yeah, I reported the issue in Stream. Please fix. Thank you.
https://steamcommunity.com/sharedfiles/filedetails/?id=1871382174&searchtext=lights

**Comment by Drseps** [comment]
Still present, lights have a 1 tile illumination.  present in Tile lights, LED lights, and the ceiling light.

**Comment by DevShadowChaos** [comment]
This issue somehow still remains in the base game for me. only the floodlight seems to work. I checked the version of the mod i'm using v2.0.0

**Comment by devent** [comment]
For me the update solved the issue. Thanks again. Try to unsub the mod and sub again. Sometimes mods needs to be deleted and added again.

**Comment by DevShadowChaos** [comment]
Just leaving this info here for people with similar issue 
 If used together with Shiny Lights (Vanilla + Spaced Out) which is currently broken all light sources except Shine bugs and the DubGate stop working.  Disableing Either mod fixes the issue
